import curses

LED_OFF = u"\u25EF "
LED_ON  = u"\u25C9 "

COLOR_PAIR_WHITE  = curses.COLOR_WHITE
COLOR_PAIR_RED    = curses.COLOR_RED
COLOR_PAIR_GREEN  = curses.COLOR_GREEN
COLOR_PAIR_YELLOW = curses.COLOR_YELLOW
COLOR_PAIR_BLUE   = curses.COLOR_BLUE

CLOCK_CYCLE = 0.1
CLOCK_CYCLE_DELTA = 0.01
